name: $(Year:yy).$(Month).$(DayOfMonth).$(rev:r)

pr: none
trigger: none

pool:
  name: Azure Pipelines
  vmImage: vs2017-win2016
  demands: java

steps:

- task: Gradle@2
  displayName: build
  inputs:
    gradleWrapperFile: source/android/gradlew.bat
    workingDirectory: source/android
    tasks: 'adaptivecards:build'
    publishJUnitResults: false

- task: Gradle@2
  displayName: 'publish'
  inputs:
    gradleWrapperFile: source/android/gradlew.bat
    workingDirectory: source/android
    tasks: 'adaptivecards:publishReleasePublicationToLocalDirectoryRepository'
    publishJUnitResults: false

- task: Powershell@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    targetType: inline
    script: |
     ls $(build.sourcesdirectory) -File -Recur | ?{
       $_.FullName -Match ".*\\io\\adaptivecards\\.*(.aar|.pom)$"
     } | %{
       cp $_.FullName (Join-Path $(build.artifactstagingdirectory) $_.Name)
       
       # Additional copy to be converted into detached PGP signature by ESRP task
       cp $_.FullName (Join-Path $(build.artifactstagingdirectory) ($_.Name + ".asc"))
     }

- task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@1
  displayName: 'ESRP CodeSign (Detached PGP)'
  inputs:
    ConnectedServiceName: 'AdaptiveCards ESRP CodeSigning'
    FolderPath: $(build.artifactstagingdirectory)
    Pattern: '*.asc'
    signConfigType: inlineSignParams
    inlineOperation: |
     [
       {
         "KeyCode":"CP-464385-Pgp",
         "OperationCode":"LinuxSign",
         "Parameters":{},
         "ToolName":"sign",
         "ToolVersion":"1.0"
       }
     ]

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'

