name: UPM-CI $(Year:yy).$(Month).$(DayOfMonth).$(rev:r)

pr: none

trigger:
  branches:
    include:
    - upm
    - upm-pipeline
  batch: True

variables:
  packageDirectory: "./artifacts/upm"

steps:
  - checkout: self

  - task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
    displayName: 'Component Detection'

  - template: Templates/publish-upm.yaml
    parameters:
      registryPath: $(registryPath)
      packageDirectory: $(packageDirectory)
      publishToFeed: true
