# This is a basic workflow that is manually triggered

name: Pack and Publish UPM

on: workflow_dispatch

jobs:
  validation:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Pack and publish
      if: github.event_name == 'push'
      run: |
        ${{ github.workspace }}/scrips/upm/pack-upm.ps1 -ProjectRoot '${{ github.workspace }}' -Version '2.7.3' -Verbose'
        ${{ github.workspace }}/scrips/upm/publish-upm.ps1 -RegistryPath 'https://pkgs.dev.azure.com/EDT/EDT/_packaging/mr.upm/npm/registry/'
      shell: pwsh
